plugins {
    id 'com.android.application'
}
android {
    namespace 'com.sycompany.iphoneduo'
    compileSdk 35
    defaultConfig {
        applicationId 'com.sycompany.iphoneduo'
        minSdk 29
        targetSdk 35
        versionCode 110
        versionName '1.1.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}
